name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
        shell: bash

      - name: Add SSH key to the agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key

      - name: Add EC2 instance to known hosts
        run: ssh-keyscan -H your-elastic-ip >> ~/.ssh/known_hosts

      - name: Pull latest changes and restart PM2
        run: |
          ssh -i ~/.ssh/deploy_key ubuntu@your-elastic-ip 'bash -s' << 'EOF'
            cd ~/Redirect_Web
            git pull origin main
            npm install
            pm2 restart redirect_web
          EOF
